export const homeCopy = {
  navigation: {
    links: [
      { id: "check-sec", label: "진단" },
      { id: "solution-sec", label: "서비스" },
      { id: "process-sec", label: "프로세스" },
      { id: "cost-sec", label: "비용" },
      { id: "pricing-sec", label: "요금제" },
      { id: "faq-sec", label: "FAQ" },
    ],
    cta: "무료 진단 받기",
  },
  hero: {
    eyebrow: "CS 운영 구독 서비스",
    title: ["상담원 채용 없이", "고객센터 운영을 시작하세요"],
    description: [
      "CS 운영 구조 설계, 자동화, 운영 리포트는 물론 실제 상담 응대까지",
      "고객센터 운영에 필요한 모든 영역을 Replo가 함께 설계하고 운영합니다.",
    ],
    primaryCta: "운영 진단 받기",
    secondaryCta: "서비스 살펴보기",
  },
  problem: {
    eyebrow: "Root Cause",
    title: ["사람을 더 뽑아도", "같은 문제가 반복된다면"],
    introduction: [
      "많은 브랜드가 고객센터 문제를 사람이 부족해서라고 생각합니다.",
      "하지만 사람을 더 채용해도 문제가 반복된다면 원인은 다른 곳에 있을 수 있습니다.",
    ],
    commonDiagnosis: {
      label: "흔한 대응",
      title: "채용과 근무 시간을 늘립니다",
      description: [
        "채용을 늘리고 더 오래 일하게 합니다.",
        "비용은 커지는데 같은 문제는 다음 달에도 반복됩니다.",
      ],
    },
    realCause: {
      label: "필요한 변화",
      title: "운영 구조부터 점검합니다",
      description: [
        "운영 구조가 없으면 사람이 바뀔 때마다 품질이 흔들립니다.",
        "Replo는 사람에 의존하지 않는 구조를 만듭니다.",
      ],
    },
  },
  checklist: {
    eyebrow: "SELF-CHECK",
    title: ["혹시, 이런 상황 아니신가요?"],
    description: "고객센터 운영을 점검하는 5가지 질문. 하나라도 해당된다면, 문제는 사람이 아니라 운영 시스템입니다.",
    items: [
      {
        icon: "refresh",
        title: "반복 문의",
        question: "고객이 같은 질문을 계속 하고 있는가",
      },
      {
        icon: "inbox",
        title: "상담 전환",
        question: "FAQ·자동응답으로 막을 수 있는 문의가 상담원에게 넘어오고 있는가",
      },
      {
        icon: "doc",
        title: "정책 정리",
        question: "취소·교환·반품·배송·A/S 기준이 상담사가 바로 답할 수 있게 정리되어 있는가",
      },
      {
        icon: "shield",
        title: "응대 품질",
        question: "상담사마다 답변 기준이 달라지고 있지 않은가",
      },
      {
        icon: "chart",
        title: "리포트",
        question: "문의 데이터를 보고 개선할 항목이 정리되고 있는가",
      },
    ],
    defaultResult: "항목을 눌러 우리 고객센터를 점검해 보세요.",
    results: [
      "1개 해당 : CS 효율 개선이 필요합니다.",
      "2개 해당 : CS 운영 효율이 낮아지고 있을 가능성이 높습니다.",
      "3개 해당 : 상담 인력보다 운영 구조 점검이 먼저 필요한 단계입니다.",
      "4개 해당 : 사람의 문제가 아니라 운영 구조 문제일 가능성이 매우 높습니다.",
      "5개 해당 : CS 운영 방식이 이미 한계에 가까운 수준입니다.",
    ],
  },
  service: {
    eyebrow: "Solution",
    title: ["Replo는 단순 상담 대행", "서비스가 아닙니다"],
    description: [
      "상담 운영부터 FAQ, 응대 기준, 반복 문의 자동화까지",
      "고객센터가 흔들리지 않도록 운영 구조를 함께 설계합니다.",
    ],
    leftFeatures: [
      { icon: "cpu", title: "AI 자동화", description: "반복 문의는 AI가 1차 응대·분류" },
      { icon: "headset", title: "상담 운영", description: "콜·채팅·게시판·이메일 통합 응대" },
      { icon: "doc", title: "SOP 설계", description: "응대 기준·스크립트를 표준화" },
    ],
    rightFeatures: [
      { icon: "shield", title: "QA 관리", description: "응대 품질을 일정하게 모니터링" },
      { icon: "target", title: "VOC 분석", description: "문의 데이터에서 개선점 도출" },
      { icon: "chart", title: "운영 리포트", description: "월간 인사이트로 운영 개선" },
    ],
    coreBadge: "CS 운영 구독",
    coreDescription: "사람 · AI · 운영 기준을 하나로 묶어, 누가 맡아도 흔들리지 않는 운영 시스템",
  },
  whyNow: {
    eyebrow: "Why Now",
    title: ["운영 구조가 없으면", "비용은 계속 커집니다"],
    cards: [
      { icon: "clock", stat: "24h", title: "고객 기대 수준이 높아졌습니다", description: "24시간 이내 응답이 기본이 됐습니다. 느린 응대는 곧 이탈과 낮은 평점으로 이어집니다." },
      { icon: "trending", stat: "시즌 ↑", title: "문의량은 계속 증가합니다", description: "브랜드가 성장할수록 CS 부담은 비례해 커집니다. 사람만 늘리는 방식은 한계가 있습니다." },
      { icon: "card", stat: "3,600만+", title: "인건비는 계속 오릅니다", description: "상담원 1명 총 고용비용은 연 3,600만 원 이상. 채용을 늘릴수록 고정비 부담이 커집니다." },
      { icon: "user", stat: "96%", title: "이탈은 조용히 일어납니다", description: "불만 고객의 96%는 아무 말 없이 떠납니다. 보이지 않는 손실이 매출을 갉아먹습니다." },
    ],
    footer: "문의량은 늘어나고, 상담원은 부족해지고, 인건비는 오릅니다.",
    footerStrong: "지금 운영 구조를 갖추는 것이 가장 확실한 비용 절감입니다.",
  },
  approach: {
    eyebrow: "Why Different",
    titlePrefix: "Replo는 상담을 대신 받는 회사가 아니라,",
    titleHighlight: "반복 문의가 줄어드는 CS 구조를 설계",
    titleSuffix: "합니다",
    description: [
      "현재 CS 운영 구조 진단 후",
      "반복 문의와 병목 구간을 빠르게 개선합니다.",
    ],
    categoryLabel: "구분",
    oldLabel: "기존 CS 외주",
    reploLabel: "Replo",
    comparisons: [
      ["운영 방식", "인력 투입 중심", "운영 구조 설계 + 인력 운영"],
      ["문의 증가 대응", "상담 인력 증원 필요", "FAQ·프로세스·자동화 설계로 반복 문의 감소"],
      ["매뉴얼 관리", "고객사 직접 정리", "정책·FAQ·응대 프로세스를 함께 설계하고 관리"],
      ["리포트", "처리 건수 중심", "VOC 유형·반복 이슈·개선 포인트 제공"],
      ["AI·자동화 활용", "AI·자동화 활용 어려움", "AI 챗봇부터 AI·자동화를 단계적으로 적용"],
      ["목표", "안정적인 응대 처리", "상담 운영 + 구조 개선 병행"],
    ],
    footerPrefix: "단순 콜센터 대행이 아니라, ",
    footerStrong: "고객센터 운영 구조 자체",
    footerSuffix: "를 설계합니다.",
  },
  expertise: {
    team: {
      eyebrow: "TEAM",
      title: "실무 경험으로 설계했습니다",
      description: [
        "Replo는 BPO 운영, 고객센터 구축, CX 전략, AI 자동화까지 12년 이상 직접",
        "경험한 팀이 만들었습니다. 이론이 아닌 현장에서 만든 운영 구조입니다.",
      ],
      stats: [
        { value: "12년+", label: "CX·고객센터 운영 경험" },
        { value: "20회+", label: "BPO 운영사 비딩·선정·관리 경험" },
        { value: "32%", label: "연간 운영비 절감 프로젝트 경험" },
        { value: "40%+", label: "응답·처리 속도 개선 경험" },
      ],
      capabilities: ["BPO 운영", "고객센터 구축", "CX 전략 수립", "SOP 설계", "QA 체계", "AI 자동화", "VOC 분석"],
    },
    experience: {
      eyebrow: "EXPERIENCE",
      title: ["다양한 카테고리 운영 경험을", "바탕으로 설계합니다"],
      categories: [
        "온라인 쇼핑몰",
        "오픈마켓",
        "자사몰 브랜드",
        "뷰티 브랜드",
        "건강·헬스케어",
        "전자기기",
        "반려동물 커머스",
        "B2B",
        "공동구매",
        "라이프스타일",
        "구독 서비스",
      ],
      noteTitle: "업종이 아니라 '운영 방식'이 경쟁력을 만듭니다",
      noteDescription:
        "상담의 핵심은 어느 산업에서나 같습니다. 문의를 유형으로 분류하고, 응대 기준(SOP)을 세우고, 데이터로 반복 개선하는 운영 체계입니다. Replo는 위 카테고리에서 이 방식을 검증해왔고, 처음 다루는 업종도 정책 인터뷰를 통해 같은 기준으로 빠르게 설계합니다. 결국 도입 성패를 가르는 것은 업종 경험이 아니라, 운영을 구조화하는 역량입니다.",
    },
  },
  onboarding: {
    eyebrow: "How It Works",
    title: "매뉴얼이 없어도 괜찮습니다",
    description: [
      "홈페이지와 판매 채널 링크만 있으면,",
      "Replo가 운영 기준 초안부터 함께 정리합니다.",
    ],
    stepPrefix: "STEP",
    steps: [
      { icon: "link", title: "URL 제출", description: "홈페이지 또는 상세페이지 링크를 전달합니다." },
      { icon: "message", title: "정책 인터뷰", description: "교환·반품·배송 등 핵심 정책을 함께 정리합니다." },
      { icon: "doc", title: "운영 기준 설계", description: "SOP·FAQ·응대 스크립트를 Replo가 설계합니다." },
      { icon: "headset", title: "운영 시작", description: "계약 후 2주 내 실제 상담 운영을 시작합니다." },
      { icon: "chart", title: "VOC 리포트", description: "운영 데이터로 월간 인사이트를 제공합니다." },
    ],
  },
  cost: {
    eyebrow: "Cost",
    title: ["상담원 1명 채용 비용으로", "운영 시스템 전체를 구축합니다"],
    description: "사람 1명을 채용하는 대신, 채용·교육·QA·리포트·AI 자동화까지 고객센터 운영에 필요한 모든 것을 갖출 수 있습니다.",
    headers: {
      item: "항목",
      hire: "직접 채용",
      hireUnit: "(월)",
      replo: "Replo Basic",
      reploUnit: "(월)",
    },
    rows: [
      { item: "기본 인건비 / 월 구독료", sub: "상담원 연봉 약 3,000만 ÷ 12", hire: "250만 원", replo: "99만 원", free: false },
      { item: "4대보험 (사업주 부담)", sub: "약 10~11%", hire: "27만 원", replo: "0원", free: true },
      { item: "채용·교육비", sub: "채용비·온보딩 교육", hire: "15만 원", replo: "0원", free: true },
      { item: "복리후생·운영 간접비", sub: "식대·장비·좌석·관리", hire: "18만 원", replo: "0원", free: true },
      { item: "SOP·QA·리포트·자동화", sub: "운영 시스템 전반", hire: "별도 구축 필요", replo: "구독에 포함", free: true },
    ],
    totalLabel: "월 합계",
    hireTotal: "약 310만 원",
    reploTotal: "99만 원",
    savingsBadge: "약 68% 저렴 ↓",
    annualLabel: "연 환산",
    annualHire: "3,720만 원",
    annualSavings: "매년 2,532만 원 절약",
    noteLabel: "산출 기준",
    note: "인건비는 직무·지역·연차에 따라 달라질 수 있으며, 위 금액은 일반적인 시장 단가를 바탕으로 한 추정치입니다.",
  },
  impact: {
    eyebrow: "Impact",
    title: ["담당자에게 의존하던 CS가", "운영 시스템으로 바뀝니다"],
    description: "누가 맡아도 같은 기준으로 응대하고, 반복 문의와 개선 포인트가 시스템에 남습니다.",
    beforeLabel: "Before",
    afterLabel: "After",
    rows: [
      { label: "담당자 의존", before: "담당자 1명에게 묶임", after: "기준이 시스템에 남음" },
      { label: "반복 문의", before: "매일 같은 답 반복", after: "반복 문의 자동 처리" },
      { label: "응대 품질", before: "사람마다 답변 다름", after: "QA로 품질 일정화" },
      { label: "개선 방식", before: "감으로 운영", after: "리포트로 개선점 발견" },
      { label: "확장 방식", before: "문의 늘면 채용으로 대응", after: "시스템으로 확장" },
    ],
    resultPrefix: "결국 ",
    result: "고객센터가 비용 센터에서 성장 자산으로 바뀝니다.",
  },
  values: {
    eyebrow: "Why Replo",
    title: "운영을 맡길 수 있는 이유",
    items: [
      { icon: "layers", title: "사람·AI·시스템을 하나로", description: "상담 인력, AI 자동화, 운영 기준을 통합합니다. Replo는 고객센터 운영에 필요한 요소를 하나의 구조로 연결해 관리합니다." },
      { icon: "gauge", title: "데이터로 증명하는 개선", description: "모든 문의가 데이터로 쌓여, 무엇을 고쳐야 할지 매월 명확해집니다." },
      { icon: "shield", title: "누가 맡아도 같은 품질", description: "SOP·QA 체계로 담당자가 바뀌어도 응대 품질이 흔들리지 않습니다." },
      { icon: "zap", title: "2주 안에 운영 시작", description: "매뉴얼이 없어도 URL 하나로 운영 기준을 설계해 빠르게 시작합니다." },
      { icon: "trending", title: "채용 없이 확장", description: "문의량이 늘어도 시스템이 받쳐줘 채용 부담 없이 성장에 대응합니다." },
      { icon: "headset", title: "책임지는 운영 파트너", description: "담당 매니저가 품질을 모니터링하고 매월 운영 인사이트를 전합니다." },
    ],
  },
  pricing: {
    eyebrow: "Pricing",
    title: "운영 규모에 맞는 플랜",
    description: "월 상담 건수 기준의 단순한 요금제. 약정 없이 시작하고 언제든 변경할 수 있습니다.",
    recommended: "Recommended",
    monthlyUnit: " / 월",
    standardCta: "이 플랜으로 시작",
    enterpriseCta: "영업팀 문의",
    detailOpen: "플랜별 기능 전체 비교",
    detailClose: "기능 비교표 접기",
    note: "모든 금액은 부가세 별도 · 초과 상담은 건당 과금됩니다.",
    plans: [
      { en: "Starter", ko: "스타터", price: "₩99,000", volume: "월 상담 50건", best: false, description: "운영 초기 브랜드가 채팅·게시판 문의를 가볍게 맡겨보는 시작 플랜", features: ["채팅·게시판 응대", "AI 응대 · 반복 문의 자동화", "FAQ 구축 · 상담 스크립트", "월간 운영 리포트"] },
      { en: "Lite", ko: "라이트", price: "₩490,000", volume: "월 상담 200건", best: false, description: "문의량이 증가하는 브랜드를 위한 기본 운영·분석 플랜", features: ["채팅·게시판·이메일 응대", "운영 인사이트 분석", "데일리 현황 알림", "월간 운영 리포트"] },
      { en: "Basic", ko: "베이직", price: "₩990,000", volume: "월 상담 500건", best: true, description: "전화·채팅·게시판·이메일을 함께 운영하며 품질을 안정화하는 성장 브랜드용", features: ["콜·채팅·게시판·이메일", "응대 가이드 제공", "교환·환불·클레임 운영", "격주 운영 리포트"] },
      { en: "Pro", ko: "프로", price: "₩1,790,000", volume: "월 상담 1,000건", best: false, description: "다채널 운영과 CS 정책 설계까지 필요한 브랜드에 적합", features: ["모든 채널 운영", "실시간 운영 대시보드", "CS 정책 설계 지원", "주간 리포트"] },
      { en: "Enterprise", ko: "엔터프라이즈", price: "별도 협의", volume: "월 상담 2,000건+", best: false, description: "전담 운영과 브랜드 맞춤 정책 설계가 필요한 대형 브랜드 맞춤 플랜", features: ["모든 채널 + 맞춤", "전담 상담 매니저", "정기 CX 운영 미팅", "API·시스템 연동"] },
    ],
    matrix: {
      featureLabel: "기능",
      bestIndex: 2,
      columns: ["스타터", "라이트", "베이직", "프로", "엔터프라이즈"],
      rows: [
        { label: "월 구독료", kind: "strong", cells: ["₩99,000", "₩490,000", "₩990,000", "₩1,790,000", "별도 협의"] },
        { label: "월 상담 제공량", kind: "strong", cells: ["50건", "200건", "500건", "1,000건", "2,000건+"] },
        { label: "상담 채널", kind: "text", cells: ["채팅·게시판", "채팅·게시판·이메일", "콜·채팅·게시판·이메일", "모든 채널", "모든 채널 + 맞춤"] },
        { label: "AI 응대 지원", kind: "check", cells: [true, true, true, true, true] },
        { label: "반복 문의 자동화", kind: "check", cells: [true, true, true, true, true] },
        { label: "데일리 현황 알림", kind: "check", cells: [true, true, true, true, true] },
        { label: "월간 운영 리포트", kind: "check", cells: [true, true, true, true, true] },
        { label: "FAQ 구축", kind: "check", cells: [true, true, true, true, true] },
        { label: "상담 스크립트", kind: "check", cells: [true, true, true, true, true] },
        { label: "운영 인사이트 분석", kind: "check", cells: [false, true, true, true, true] },
        { label: "응대 가이드 제공", kind: "check", cells: [false, false, true, true, true] },
        { label: "CS 정책 설계 지원", kind: "check", cells: [false, false, false, true, true] },
        { label: "실시간 운영 대시보드", kind: "check", cells: [false, false, false, true, true] },
        { label: "전담 상담 매니저", kind: "check", cells: [false, false, false, false, true] },
        { label: "정기 CX 운영 미팅", kind: "check", cells: [false, false, false, false, true] },
      ],
    },
  },
  faq: {
    eyebrow: "FAQ",
    title: "자주 묻는 질문",
    items: [
      ["매뉴얼이 없어도 도입 가능한가요?", "가능합니다. 홈페이지, 상세페이지, 기존 문의 내용을 바탕으로 예상 질문과 운영 기준을 먼저 정리합니다. 완성된 자료가 없어도 시작할 수 있습니다."],
      ["AI 챗봇만 제공하는 서비스인가요?", "아닙니다. AI 활용은 일부입니다. 반복 문의와 기준이 명확한 문의는 자동화하고, 예외·민감 문의는 사람이 처리합니다. 상담 운영과 운영 기준 설계가 핵심입니다."],
      ["Replo는 BPO인가요?", "상담 인력도 제공하지만 단순 BPO는 아닙니다. Replo의 핵심은 사람·AI·운영 기준을 하나의 시스템으로 묶는 것입니다."],
      ["정말 2주 안에 시작 가능한가요?", "기본 자료 확인과 정책 인터뷰가 완료되면 약 2주 내 운영 시작을 목표로 합니다. 기존 FAQ·상세페이지·정책 문서가 있으면 더 빠릅니다."],
      ["기존 상담사를 유지하면서 사용할 수 있나요?", "가능합니다. 기존 담당자는 유지하고 Replo가 반복 문의, 운영 기준 정리, 리포트, 자동화 영역을 보완하는 방식으로도 운영할 수 있습니다."],
      ["소규모 브랜드나 문의량이 적어도 가능한가요?", "가능합니다. Starter 플랜은 월 50건 규모의 초기 브랜드도 이용할 수 있도록 설계했습니다. 문의량이 적을수록 채용보다 구독 방식이 유리합니다."],
      ["자동화 세팅도 해주나요?", "운영 데이터를 기반으로 반복 문의, 누락 체크, 리포트 등 자동화 가능한 영역을 설계하고 단계적으로 적용할 수 있도록 돕습니다."],
      ["계약 기간과 플랜 변경은 어떻게 되나요?", "3개월 의무 사용 후 월 단위로 이용 가능합니다. 운영 중 문의량과 채널이 늘어나면 상위 플랜으로 확장할 수 있으며, 초과 사용이 잦으면 안내해 드립니다."],
    ],
  },
  finalCta: {
    title: ["CS가 문제라고 느껴진다면,", "Replo 운영 진단부터 신청하세요."],
    description: [
      "무료 진단으로 현재 CS 병목을 확인하고,",
      "Replo가 대신 운영할 수 있는 범위와 빠른 온보딩 방향을 안내드립니다.",
    ],
    button: "무료 운영 진단 받기",
    secondaryButton: "서비스 문의하기",
    hint: "문의 · sales@replo.kr",
  },
  footer: {
    description: "상담원 채용 대신, 고객센터 운영을 구독하세요. AI와 운영 전문가가 SOP·QA·자동화·리포트까지 하나의 시스템으로 운영합니다.",
    serviceTitle: "서비스",
    serviceLinks: [
      { href: "#solution-sec", label: "운영 시스템" },
      { href: "#approach-sec", label: "방식의 차이" },
      { href: "#process-sec", label: "시작 방법" },
      { href: "#pricing-sec", label: "요금제" },
    ],
    companyTitle: "회사",
    companyLinks: [
      { href: "#check-sec", label: "자가 점검" },
      { href: "#cost-sec", label: "비용 절감" },
      { href: "#faq-sec", label: "FAQ" },
    ],
    informationTitle: "회사 정보",
    companyName: "(주)아빈코퍼레이션",
    representative: "대표자 김지민",
    address: "경기도 구리시 갈매중앙로 190, A동 10005호",
    businessNumber: "사업자등록번호 191-88-03596",
    contact: "Contact sales@replo.kr",
    telephone: "Tel 010-8006-5444",
    copyright: "© 2026 (주)아빈코퍼레이션",
    slogan: "상담원 채용 대신, 고객센터 운영을 구독하세요.",
  },
} as const;
